# -*- coding: utf-8 -*-
"""h8dsft_converter.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ImXDph9IGsc_5o3962rEap6wOuxFcoLg
"""

def kelvin_to_celcius(kelvin):
    """
    Mengkonversi suhu dari kelvin ke celcius.
    
    Args:
    kelvin -- suhu dalam kelvin
    
    Returns:
    suhu dalam celcius
    """
    celcius = kelvin - 273.15
    return celcius


def celcius_to_kelvin(celcius):
    """
    Mengkonversi suhu dari celcius ke kelvin.
    
    Args:
    celcius -- suhu dalam celcius
    
    Returns:
    suhu dalam kelvin
    """
    kelvin = celcius + 273.15
    return kelvin


def suhu_to_fahrenheit(suhu, from_scale):
    """
    Mengkonversi suhu dari kelvin atau celcius ke fahrenheit.
    
    Args:
    suhu -- suhu dalam kelvin atau celcius
    from_scale -- skala suhu awal, 'kelvin' atau 'celcius'
    
    Returns:
    suhu dalam fahrenheit
    """
    if from_scale == 'kelvin':
        celcius = kelvin_to_celcius(suhu)
    elif from_scale == 'celcius':
        celcius = suhu
    else:
        raise ValueError("Invalid scale, should be 'kelvin' or 'celcius'")
        
    fahrenheit = celcius * 9/5 + 32
    return fahrenheit


def suhu_from_fahrenheit(fahrenheit, to_scale):
    """
    Mengkonversi suhu dari fahrenheit ke kelvin atau celcius.
    
    Args:
    fahrenheit -- suhu dalam fahrenheit
    to_scale -- skala suhu tujuan, 'kelvin' atau 'celcius'
    
    Returns:
    suhu dalam kelvin atau celcius
    """
    celcius = (fahrenheit - 32) * 5/9
    
    if to_scale == 'kelvin':
        kelvin = celcius_to_kelvin(celcius)
        return kelvin
    elif to_scale == 'celcius':
        return celcius
    else:
        raise ValueError("Invalid scale, should be 'kelvin' or 'celcius'")